import asyncio
import time
import sys
import os

sys.path.insert(0, os.path.abspath('.'))
from playwright.async_api import async_playwright

async def test_speed():
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        context = await browser.new_context()
        page = await context.new_page()
        
        captured = []
        
        async def route_handler(route):
            req = route.request
            if 'api.debank.com' in req.url and 'x-api-sign' in req.headers:
                captured.append(req.headers)
                await route.abort()
            else:
                await route.continue_()
                
        await page.route("**/*", route_handler)
        
        wallet = "0x463452C356322D463B84891eBDa33DAED274cB40"
        print("\nLoading DeBank clean...")
        await page.goto(f"https://debank.com/profile/{wallet.lower()}", wait_until="networkidle", timeout=20000)
        
        print("Waiting for any natural signatures to be generated by DeBank itself...")
        await asyncio.sleep(5)
        
        print(f"Captured {len(captured)} natural signatures from the app's own requests.")
        
        await browser.close()

if __name__ == "__main__":
    asyncio.run(test_speed())
